### ISSUE TITLE
Custom queries

### ISSUE THREAD

**Issue by gabro** [contactlab/contacthub-sdk-scala#13]
[Trello card](https://trello.com/c/58c94db5e7993d7de01db768/)

## requirements
Provide the custom query functionality, as soon as it lands on the Java SDK.

## specs
- Add support for inheritance and interfaces to the model generator.
- Wrap the Java SDK call as usual.

**Comment by dhinus** [comment]
@gabro this can be closed right? Implemented in a0d276eaf99b6feb848e26e0845c7cd4c72c810e.

**Comment by gabro** [comment]
Absolutely :)
